version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -jar build-scripts/Build.jar --all --output ./out/jars --include EducationalBottersApi
artifacts:
  files:
    - '**/*'
  discard-paths: no